name: New Command
description: Create a feature request for a new command
labels: ["feature request", "new command", "triage required"]
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! We are currently testing out a beta of the new [Issue Forms](https://github.blog/changelog/2021-06-23-whats-new-with-github-issues/).
  - type: textarea
    attributes:
      label: "Summarize Functionality"
      description: "Please provide a clear/concise description of what problem the new command will solve."
    validations:
      required: true
  - type: dropdown
    id: existing-command
    attributes:
      label: "Is this a wrapper command that will utilize current commands already in the module?"
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: dropdown
    id: api-endpoint
    attributes:
      label: "Is this a command based on a REST API endpoint?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: version-specific
    attributes:
      label: "Is the endpoint only found in a specific version of Secret Server"
      description: "If so please provide the version of Secret Server in the Technical Details."
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Technical Details"
      description: "Provide the API endpoint, links to concepts, example code or write-ups of the desired functionality."
    validations:
      required: false